<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\Auth\" />
    <Folder Include="Dtos\Cart\Cartitem\" />
    <Folder Include="Dtos\Category\" />
    <Folder Include="Dtos\Payment\" />
    <Folder Include="Dtos\Order\OrderItem\" />
    <Folder Include="Dtos\Product\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
