--CREATE PRODUCT TABLE
CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY(1,1),
	ProductName NVARCHAR(100) NOT NULL,
	Price INT NOT NULL,
	[Description] NVARCHAR(MAX),
	ImageUrl NVARCHAR(MAX),
	CategoryId INT,
	Stock INT NOT NULL,

	CONSTRAINT CHK_Products_Price CHECK(Price > 0),
	CONSTRAINT CHK_Products_Stock CHECK(Stock >= 0)
)
GO
CREATE NONCLUSTERED INDEX IX_ProductName
ON Products(ProductName)
GO

--CREATE CATEGORY TABLE
CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(200) NOT NULL

	CONSTRAINT UQ_Categories_Title UNIQUE(Title)
)


GO

-- CREATE CART TABLE
CREATE TABLE Carts(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId nvarchar(450) NOT NULL
)
GO

--CREATE CARTITEM TABLE
CREATE TABLE CartItems(
	Id INT PRIMARY KEY IDENTITY(1,1),
	CartId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	
	CONSTRAINT CHK_CartItems_Quantity CHECK (Quantity > 0)
)
GO

--CREATE ORDER TABLE
CREATE TABLE Orders(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserId nvarchar(450) NOT NULL
)

GO

--CREATE ORDERITEM TABLE
CREATE TABLE OrderItems(
	Id INT PRIMARY KEY IDENTITY(1,1),
	OrderId INT NOT NULL,
	ProductId INT NOT NULL,
	UnitPrice INT NOT NULL,
	Quantity INT NOT NULL,

	CONSTRAINT CHK_OrderItems_Quantity CHECK (Quantity > 0)
)
GO

--CREATE PAYMENT TABLE
CREATE TABLE Payments(
	Id INT PRIMARY KEY IDENTITY(1,1),
	OrderId INT NOT NULL,
	Amount INT,
	[Status] NVARCHAR(20) NOT NULL DEFAULT 'Wating',
	CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)